#!/usr/bin/env node
var SparqlDatasource = require('./lib/SparqlDatasource'),
    LinkedDataFragmentsServer = require('./lib/LinkedDataFragmentsServer'),
    dbpedia = new SparqlDatasource('http://dbpedia.org/sparql', 'http://dbpedia.org'),
    server = new LinkedDataFragmentsServer({ dbpedia: dbpedia });

var port = 3000;
console.log('Running on http://localhost:' + port + '/');
server.listen(port);
