/*! @license MIT ©2015-2016 Miel Vander Sande - Ghent University / iMinds */
/* A SummaryRdfViewExtension extends the Triple Pattern Fragments RDF view with a summary link. */

var RdfView = require('../RdfView');

var ds = 'http://semweb.mmlab.be/ns/datasummaries#';

// Creates a new SummaryRdfViewExtension
function SummaryRdfViewExtension(settings) {
  if (!(this instanceof SummaryRdfViewExtension))
    return new SummaryRdfViewExtension(settings);
  RdfView.call(this, 'TriplePatternFragments:After', settings);
}
RdfView.extend(SummaryRdfViewExtension);

// Generates triples and quads by sending them to the data and/or metadata callbacks
SummaryRdfViewExtension.prototype._generateRdf = function (settings, data, metadata, done) {
  // If summaries are enabled, connect the datasource to its summary
  // TODO: summary should be of/off per dataset
  if (settings.summaries && settings.summaries.enabled) {
    // TODO: summary URL should be generated by router
    metadata(settings.datasource.url, ds + 'hasDatasetSummary',
             settings.baseURL + 'summaries/' + encodeURIComponent(settings.query.datasource));
  }
  done();
};

module.exports = SummaryRdfViewExtension;
