/*! @license MIT ©2015-2018 Ruben Verborgh and Ruben Taelman, Ghent University - imec */
/** A QuadPatternFragmentsController responds to requests for TPFs and QPFs */

import { Controller } from '@ldf/core/lib/controllers/Controller';
import * as url from 'url';
import * as _ from 'lodash';
import type { ParsedUrlQuery } from 'querystring';
import type { ControllerOptions, LdfRequest, LdfResponse, Query, RouterRequest, ViewSettings } from '@ldf/core';
import type { Datasource } from '@ldf/core/lib/datasources/Datasource';

interface Router {
  extractQueryParams(request: RouterRequest, query: Query): void;
}

interface QuadPatternFragmentsControllerOptions extends ControllerOptions {
  routers?: Router[];
  extensions?: Controller[];
}

// Creates a new QuadPatternFragmentsController
export class QuadPatternFragmentsController extends Controller {
  viewName: string;
  protected _routers: Router[];
  protected _extensions: Controller[];

  constructor(options?: QuadPatternFragmentsControllerOptions) {
    options = options || {};
    super(options);
    this._routers = options.routers || [];
    this._extensions = options.extensions || [];

    this.viewName = 'QuadPatternFragments';
  }

  // The required features the given datasource must have
  supportsDatasource(datasource: Datasource): boolean {
    return datasource.supportedFeatures.triplePattern ||
          datasource.supportedFeatures.quadPattern;
  }

  // Try to serve the requested fragment
  protected override _handleRequest(request: LdfRequest, response: LdfResponse, next: (error?: Error) => void): void {
    // Create the query from the request by calling the fragment routers
    let requestParams = { url: request.parsedUrl, headers: request.headers } as RouterRequest,
        query = this._routers.reduce((query: Query, router) => {
          try { router.extractQueryParams(requestParams, query); }
          catch (e) { /* ignore routing errors */ }
          return query;
        }, { features: {} });

    // Execute the query on the data source
    let datasource = query.features!.datasource && this._datasources[query.datasource!];
    delete query.features!.datasource;
    if (!datasource || !datasource.supportsQuery(query) ||
      !this.supportsDatasource(datasource))
      return next();

    // Generate the query result
    let view = this._negotiateView(this.viewName, request, response),
        settings = this._createFragmentMetadata(request, query, datasource);
    settings.results = datasource.select(query,
      (error) => { error && next(error); });

    // Execute the extensions and render the query result
    let extensions = this._extensions, extensionId = 0;
    (function nextExtension(error?: Error) {
      // Log a possible error with the previous extension
      if (error)
        process.stderr.write((error.stack || String(error)) + '\n');
      // Execute the next extension
      if (extensionId < extensions.length)
        extensions[extensionId++].handleRequest(request, response, nextExtension, settings);
      // Render the query result
      else
        view.render(settings, request, response);
    })();
  }

  // Create the template URL for requesting quad patterns
  protected _createTemplateUrl(datasourceUrl: string, supportsQuads: boolean): string {
    return datasourceUrl + (!supportsQuads ? '{?subject,predicate,object}' :
      '{?subject,predicate,object,graph}');
  }

  // Create parameterized pattern string for quad patterns
  protected _createPatternString(query: Query, supportsQuads: boolean): string {
    // Serialize subject and predicate IRIs or variables
    let subject   = query.subject   ? '<' + query.subject.value   + '> ' : '?s ',
        predicate = query.predicate ? '<' + query.predicate.value + '> ' : '?p ',
        // Serialize object IRI, literal, or variable
        object = query.object && query.object.termType === 'NamedNode' ? '<' + query.object.value + '> ' :
          query.object ? query.object.value : '?o',
        graph = '';
    // Serialize graph IRI, default graph, or variable
    if (supportsQuads) {
      if (query.graph && query.graph.termType === 'DefaultGraph') graph = ' @default';
      else if (query.graph)   graph = ' <' + query.graph.value + '>';
      else                    graph = ' ?g';
    }
    // Join them in a pattern
    return '{ ' + subject + predicate + object + graph + '. }';
  }

  // Creates metadata about the requested fragment
  protected _createFragmentMetadata(request: LdfRequest, query: Query, datasourceSettings: Datasource): ViewSettings {
    // TODO: these URLs should be generated by the routers
    let requestUrl = request.parsedUrl!,
        // maintain the originally requested query string to avoid encoding differences
        origQuery = request.url!.replace(/[^?]+/, ''),
        pageUrl = url.format(requestUrl).replace(/\?.*/, origQuery),
        paramsNoPage = _.omit(requestUrl.query as ParsedUrlQuery, 'page'),
        currentPage = parseInt((requestUrl.query as ParsedUrlQuery).page as string, 10) || 1,
        datasourceUrl = url.format(_.omit(requestUrl, 'query')),
        fragmentUrl = url.format({ ...requestUrl, query: paramsNoPage }),
        fragmentPageUrlBase = fragmentUrl + (/\?/.test(fragmentUrl) ? '&' : '?') + 'page=',
        indexUrl = url.format(_.omit(requestUrl, 'search', 'query', 'pathname')) + '/';

    // Generate a textual representation of the pattern
    let supportsQuads = datasourceSettings.supportedFeatures.quadPattern || false;
    query.patternString = this._createPatternString(query, supportsQuads);

    return {
      datasource: _.assign(datasourceSettings, {
        index: indexUrl + '#dataset',
        url: datasourceUrl + '#dataset',
        templateUrl: this._createTemplateUrl(datasourceUrl, supportsQuads),
        supportsQuads: supportsQuads,
      }),
      fragment: {
        url: fragmentUrl,
        pageUrl: pageUrl,
        firstPageUrl: fragmentPageUrlBase + '1',
        nextPageUrl: fragmentPageUrlBase + (currentPage + 1),
        previousPageUrl: currentPage > 1 ? fragmentPageUrlBase + (currentPage - 1) : null,
      },
      query: query,
      prefixes: this._prefixes,
      datasources: this._datasources,
    };
  }

  // Close all data sources
  override close(): void {
    for (let datasourceName in this._datasources) {
      try { this._datasources[datasourceName].close(); }
      catch (error) { /* ignore closing errors */ }
    }
  }
}

