/*! @license ©2015 Ruben Verborgh - Multimedia Lab / iMinds / Ghent University */

/** A TriplePatternFragmentsController responds to requests for fragments */

var Controller = require('./Controller'),
    url = require('url'),
    _ = require('lodash'),
    N3Util = require('n3').Util,
    Util = require('../Util');

// Creates a new TriplePatternFragmentsController
function TriplePatternFragmentsController(options) {
  if (!(this instanceof TriplePatternFragmentsController))
    return new TriplePatternFragmentsController(options);
  options = options || {};
  Controller.call(this, options);
  this._routers = options.routers || [];

  // Configure memento settings
  var timegates = options.timegates || {};
  this._timegateBaseUrl = timegates.baseURL || '/timegate/';
  var map = this._timegateMap = {};
  _.forIn(timegates.mementos || {}, function (setting, key) {
    setting.versions.forEach(function (entry) {
      map[entry] = { memento: key, original: setting.originalBaseURL };
    });
  });
}
Controller.extend(TriplePatternFragmentsController);

// Try to serve the requested fragment
TriplePatternFragmentsController.prototype._handleRequest = function (request, response, next) {
  // Create the query from the request by calling the fragment routers
  var requestParams = { url: request.parsedUrl },
      query = this._routers.reduce(function (query, router) {
    try { router.extractQueryParams(requestParams, query); }
    catch (e) { /* ignore routing errors */ }
    return query;
  }, { features: [] });

  // Execute the query on the data source
  var datasourceSettings = query.features.datasource && this._datasources[query.datasource];
  delete query.features.datasource;
  if (!datasourceSettings || !datasourceSettings.datasource.supportsQuery(query))
    return next();

  // Write memento links
  this._createFragmentTimegate(request, response, query.datasource, datasourceSettings);

  // Write the query result
  var view = this._negotiateView('TriplePatternFragments', request, response),
      settings = this._createFragmentMetadata(request, query, datasourceSettings);
  settings.resultStream = datasourceSettings.datasource.select(query,
                          function (error) { error && next(error); });
  view.render(settings, request, response);
};

// Configure Memento Timegate functionality
TriplePatternFragmentsController.prototype._createFragmentTimegate =
function (request, response, datasource, datasourceSettings) {
  var origQuery = request.url.replace(/[^?]+/, '');
  if (datasourceSettings.memento) {   // Is resource a memento?
    var mementoSettings = datasourceSettings.memento;
    if (!mementoSettings.interval || mementoSettings.interval.length < 1 || mementoSettings.interval.length > 2)
      return;

    var datetime = new Date(mementoSettings.interval[0]).toUTCString(),
        timegate = url.format(_.defaults({ pathname: this._timegateBaseUrl + this._timegateMap[datasource].memento }, request.parsedUrl)),
        origurl = this._timegateMap[datasource].original ?
                  this._timegateMap[datasource].original + origQuery : url.format(_.defaults({ pathname: this._timegateMap[datasource].memento }, request.parsedUrl));

    response.setHeader('Link', '<' + origurl + '>;rel=original, <' + timegate + '>;rel=timegate');
    response.setHeader('Memento-Datetime', datetime);
   } else { // Add timegate link if resource is not a memento
     var timegateSettings = datasourceSettings.timegate;
     // When timegate config is true, use local timegate
     if (timegateSettings === true)
       response.setHeader('Link', '<' + url.format(_.defaults({ pathname: this._timegateBaseUrl + datasource }, request.parsedUrl)) + '>;rel=timegate');
     else if (timegateSettings)
       response.setHeader('Link', '<' + timegateSettings + origQuery + '>;rel=timegate');
  }
};

// Creates metadata about the requested fragment
TriplePatternFragmentsController.prototype._createFragmentMetadata =
function (request, query, datasourceSettings) {
  // TODO: these URLs should be generated by the routers
  var requestUrl = request.parsedUrl,
      // maintain the originally requested query string to avoid encoding differences
      origQuery = request.url.replace(/[^?]+/, ''),
      pageUrl = url.format(requestUrl).replace(/\?.*/, origQuery),
      paramsNoPage = _.omit(requestUrl.query, 'page'),
      currentPage = parseInt(requestUrl.query.page, 10) || 1,
      datasourceUrl = url.format(_.omit(requestUrl, 'query')),
      fragmentUrl = url.format(_.defaults({ query: paramsNoPage }, requestUrl)),
      fragmentPageUrlBase = fragmentUrl + (/\?/.test(fragmentUrl) ? '&' : '?') + 'page=',
      indexUrl = url.format(_.omit(requestUrl, 'search', 'query', 'pathname')) + '/';

  // Generate a textual representation of the pattern
  query.patternString = '{ ' +
    (query.subject              ? '<' + query.subject   + '> ' : '?s ') +
    (query.predicate            ? '<' + query.predicate + '> ' : '?p ') +
    (N3Util.isIRI(query.object) ? '<' + query.object    + '> ' : (query.object || '?o')) + ' }';

  return {
    datasource: _.assign(_.omit(datasourceSettings, 'datasource'), {
      index: indexUrl + '#dataset',
      url: datasourceUrl + '#dataset',
      templateUrl: datasourceUrl + '{?subject,predicate,object}',
    }),
    fragment: {
      url: fragmentUrl,
      pageUrl: pageUrl,
      firstPageUrl: fragmentPageUrlBase + '1',
      nextPageUrl: fragmentPageUrlBase + (currentPage + 1),
      previousPageUrl: currentPage > 1 ? fragmentPageUrlBase + (currentPage - 1) : null,
    },
    query: query,
    prefixes: this._prefixes,
    datasources: this._datasources,
  };
};

// Close all data sources
TriplePatternFragmentsController.prototype.close = function () {
  for (var datasourceName in this._datasources) {
    try { this._datasources[datasourceName].datasource.close(); }
    catch (error) { }
  }
};

module.exports = TriplePatternFragmentsController;
