/*! @license MIT ©2015-2016 Miel Vander Sande, Ghent University - imec */
/* A SummaryRdfViewExtension extends the Quad Pattern Fragments RDF view with a summary link. */

import { RdfView } from '@ldf/core/lib/views/RdfView';
import type { Quad } from 'rdf-js';
import type { RdfViewSettings, RenderDone, ViewSettings } from '@ldf/core';
import type { SummaryRenderSettings } from '../../controllers/SummaryController';

type SummaryViewSettings = ViewSettings & SummaryRenderSettings;

const ds = 'http://semweb.mmlab.be/ns/datasummaries#';

// Creates a new SummaryRdfViewExtension
export class SummaryRdfViewExtension extends RdfView {
  public constructor(settings: RdfViewSettings) {
    super('QuadPatternFragments:After', settings);
  }

  // Generates triples and quads by sending them to the data and/or metadata callbacks
  protected override _generateRdf(settings: SummaryViewSettings, data: (quad: Quad) => void, metadata: (quad: Quad) => void, done: RenderDone): void {
    // If summaries are enabled, connect the datasource to its summary
    // TODO: summary should be of/off per dataset
    const summaries = settings.summaries;
    const datasource = settings.datasource;
    const query = settings.query;
    if (summaries && (summaries.dir || summaries.path)) {
      // TODO: summary URL should be generated by router
      if (datasource.url && settings.baseURL && query.datasource) {
        metadata(this.dataFactory.quad(this.dataFactory.namedNode(datasource.url), this.dataFactory.namedNode(ds + 'hasDatasetSummary'),
          this.dataFactory.namedNode(settings.baseURL + 'summaries/' + encodeURIComponent(query.datasource))));
      }
    }
    done();
  }
}

