/*! @license MIT ©2015-2016 Ruben Verborgh, Ghent University - imec */
/* A SummaryHtmlViewExtension extends the Quad Pattern Fragments RDF view with a summary link. */

import { HtmlView } from '@ldf/core/lib/views/HtmlView';
import * as path from 'path';
import type { LdfRequest, LdfResponse, RenderDone, ViewSettings } from '@ldf/core';
import type { SummaryRenderSettings } from '../../controllers/SummaryController';

type SummaryViewSettings = ViewSettings & Omit<SummaryRenderSettings, 'datasource'>;

// Creates a new SummaryHtmlViewExtension
export class SummaryHtmlViewExtension extends HtmlView {
  public constructor(settings?: ViewSettings) {
    super('QuadPatternFragments:Before', settings);
  }

  // Renders the view with the given settings to the response
  protected override _render(settings: SummaryViewSettings, request: LdfRequest, response: LdfResponse, done: RenderDone): void {
    // If summaries are enabled, connect the datasource to its summary
    // TODO: summary should be of/off per dataset
    const summaries = settings.summaries;
    if (summaries && (summaries.dir || summaries.path) && settings.baseURL && settings.query.datasource) {
      // TODO: summary URL should be generated by router
      settings.summary = {
        url: settings.baseURL + 'summaries' + encodeURIComponent(settings.query.datasource),
      };
      this._renderTemplate(path.join(__dirname, 'summary-link'), settings, request, response, done);
    }
    else
      done();
  }
}


