/*! @license MIT ©2015-2016 Ruben Verborgh, Ghent University - imec */
/* A SummaryHtmlViewExtension extends the Quad Pattern Fragments RDF view with a summary link. */

import HtmlView = require('@ldf/core/lib/views/HtmlView');
import * as path from 'path';
import type { LdfRequest, LdfResponse, RenderDone, ViewSettings } from '@ldf/core/lib/types';

// Creates a new SummaryHtmlViewExtension
class SummaryHtmlViewExtension extends HtmlView {
  constructor(settings?: ViewSettings) {
    super('QuadPatternFragments:Before', settings);
  }

  // Renders the view with the given settings to the response
  protected override _render(settings: ViewSettings, request: LdfRequest, response: LdfResponse, done: RenderDone): void {
    // If summaries are enabled, connect the datasource to its summary
    // TODO: summary should be of/off per dataset
    if (settings.summaries && (settings.summaries.dir || settings.summaries.path)) {
      // TODO: summary URL should be generated by router
      settings.summary = {
        url: settings.baseURL + 'summaries' + encodeURIComponent(settings.query.datasource),
      };
      this._renderTemplate(path.join(__dirname, 'summary-link'), settings, request, response, done);
    }
    else
      done();
  }
}


export = SummaryHtmlViewExtension;
