/*! @license MIT ©2015-2016 Miel Vander Sande, Ghent University - imec */
/* A SummaryRdfViewExtension extends the Quad Pattern Fragments RDF view with a summary link. */

import RdfView = require('@ldf/core/lib/views/RdfView');
import type { Quad } from 'rdf-js';
import type { RenderDone, ViewSettings } from '@ldf/core/lib/types';

let ds = 'http://semweb.mmlab.be/ns/datasummaries#';

// Creates a new SummaryRdfViewExtension
class SummaryRdfViewExtension extends RdfView {
  constructor(settings?: ViewSettings) {
    super('QuadPatternFragments:After', settings);
  }

  // Generates triples and quads by sending them to the data and/or metadata callbacks
  protected override _generateRdf(settings: ViewSettings, data: (quad: Quad) => void, metadata: (quad: Quad) => void, done: RenderDone): void {
    // If summaries are enabled, connect the datasource to its summary
    // TODO: summary should be of/off per dataset
    if (settings.summaries && ((settings.summaries as { dir?: string; path?: string }).dir || (settings.summaries as { dir?: string; path?: string }).path)) {
      // TODO: summary URL should be generated by router
      if ((settings.datasource as { url?: string }).url && settings.baseURL  && (settings.query as { datasource?: string }).datasource)        {
        metadata(this.dataFactory!.quad(this.dataFactory!.namedNode((settings.datasource as { url?: string }).url as string), this.dataFactory!.namedNode(ds + 'hasDatasetSummary'),
          this.dataFactory!.namedNode((settings.baseURL as string) + 'summaries/' + encodeURIComponent((settings.query as { datasource?: string }).datasource as string))));
      }
    }
    done();
  }
}

export = SummaryRdfViewExtension;
