/*! @license MIT ©2015-2016 Ruben Verborgh, Ghent University - imec */
/* A SummaryHtmlViewExtension extends the Quad Pattern Fragments RDF view with a summary link. */

import HtmlView = require('@ldf/core/lib/views/HtmlView');
import * as path from 'path';
import type { LdfRequest, LdfResponse, Query, RenderDone, ViewSettings } from '@ldf/core/lib/types';
import type { SummariesConfig } from '../../controllers/SummaryController';

// Creates a new SummaryHtmlViewExtension
class SummaryHtmlViewExtension extends HtmlView {
  constructor(settings?: ViewSettings) {
    super('QuadPatternFragments:Before', settings);
  }

  // Renders the view with the given settings to the response
  protected override _render(settings: ViewSettings, request: LdfRequest, response: LdfResponse, done: RenderDone): void {
    // If summaries are enabled, connect the datasource to its summary
    // TODO: summary should be of/off per dataset
    let summaries = settings.summaries as SummariesConfig | undefined;
    if (summaries && (summaries.dir || summaries.path)) {
      // TODO: summary URL should be generated by router
      settings.summary = {
        url: (settings.baseURL as string) + 'summaries' + encodeURIComponent((settings.query as Query).datasource as string),
      };
      this._renderTemplate(path.join(__dirname, 'summary-link'), settings, request, response, done);
    }
    else
      done();
  }
}


export = SummaryHtmlViewExtension;
