/*! @license MIT ©2015-2016 Ruben Verborgh, Ghent University - imec */
/* A SummaryHtmlViewExtension extends the Quad Pattern Fragments RDF view with a summary link. */

var HtmlView = require('@ldf/core').views.HtmlView,
    path = require('path');

// Creates a new SummaryHtmlViewExtension
function SummaryHtmlViewExtension(settings) {
  if (!(this instanceof SummaryHtmlViewExtension))
    return new SummaryHtmlViewExtension(settings);
  HtmlView.call(this, 'QuadPatternFragments:Before', settings);
}
HtmlView.extend(SummaryHtmlViewExtension);

// Renders the view with the given settings to the response
SummaryHtmlViewExtension.prototype._render = function (settings, request, response, done) {
  // If summaries are enabled, connect the datasource to its summary
  // TODO: summary should be of/off per dataset
  if (settings.summaries) {
    // TODO: summary URL should be generated by router
    settings.summary = {
      url: settings.baseURL + 'summaries/' + encodeURIComponent(settings.query.datasource),
    };
    this._renderTemplate(path.join(__dirname, 'summary-link'), settings, request, response, done);
  }
  else
    done();
};

module.exports = SummaryHtmlViewExtension;
